<a href="https://colab.research.google.com/github/JiteshKumar9/Women-Cloth-Reviews-Prediction-with-Multi-Nomial-Naive-Bayes/blob/main/Women_Cloth_Reviews_Prediction_with_Multi_Nomial_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>





# Women Cloth Reviews Prediction with Multi Nomial Naive Bayes

The multinomial Naive Bayes classifier is suitable for classification of discrete features(e.g., word counts for text classification). The multinomial distribution normally requires interger feature counts. However in practice, fractional counts such as tf-idf may also work.

# Import Library

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
import matplotlib as plt

In [ ]:
import seaborn as sns

# Import Dataset

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/JiteshKumar0/Datasets/main/Womens%20Clothing%20E-Commerce%20Reviews.csv')

In [ ]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [ ]:
df.shape

(23486, 11)

# Missing Values

Remove missing values in Reviews columns with No Review text

In [ ]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [ ]:
df[df['Review Text']==""]=np.NaN

In [ ]:
df['Review Text'].fillna("No Review Text",inplace=True)

In [ ]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [ ]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

# Define Target(y) and Feature(X)

In [ ]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [ ]:
X = df['Review Text']

In [ ]:
y = df['Rating']

In [ ]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

# Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7, stratify = y, random_state = 2529)

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

# Get Feature Text Conversion to Tokens

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv= CountVectorizer(lowercase = True, analyzer='word', ngram_range=(2, 3), stop_words = 'english', max_features=5000)

In [ ]:
X_train = cv.fit_transform(X_train)

In [ ]:
cv.get_feature_names_out()

array(['10 12', '10 bought', '10 fit', ..., 'yellow color', 'yoga pants',
       'zipper little'], dtype=object)

In [ ]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_test = cv.fit_transform(X_test)

In [ ]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'years come', 'years old',
       'yoga pants'], dtype=object)

In [ ]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# Get Model Train

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model = MultinomialNB()

In [ ]:
model.fit(X_train, y_train)

MultinomialNB()

# Get Model Prediction

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred.shape

(7046,)

In [ ]:
y_pred

array([4., 4., 5., ..., 5., 5., 4.])

# Get Probability of Each Predicted Class

In [ ]:
model.predict_proba(X_test)

array([[9.61627846e-02, 1.21587107e-01, 2.61053999e-01, 4.15632757e-01,
        1.05563352e-01],
       [1.52260754e-01, 2.00471990e-02, 2.96168321e-01, 3.28511250e-01,
        2.03012477e-01],
       [3.45951842e-02, 4.19250461e-02, 1.46458042e-01, 2.58410083e-01,
        5.18611644e-01],
       ...,
       [4.40456735e-02, 1.13409468e-02, 2.65711717e-02, 7.56260955e-02,
        8.42416112e-01],
       [7.25608901e-03, 3.03718334e-04, 5.58927047e-03, 4.54625587e-01,
        5.32225335e-01],
       [1.30506112e-01, 7.21920545e-02, 1.13371567e-02, 4.43923937e-01,
        3.42040740e-01]])

# Get Model Evaluation

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[  25   25   45   33  125]
 [  41   55   67   84  223]
 [  76   85  140  181  379]
 [ 174  108  185  364  692]
 [ 440  246  354  681 2218]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.03      0.10      0.05       253
         2.0       0.11      0.12      0.11       470
         3.0       0.18      0.16      0.17       861
         4.0       0.27      0.24      0.25      1523
         5.0       0.61      0.56      0.59      3939

    accuracy                           0.40      7046
   macro avg       0.24      0.24      0.23      7046
weighted avg       0.43      0.40      0.41      7046



# Recategories Rating as Poor (0) and Good(1)

In [ ]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

**Re-Rating as 1,2,3 as 0 and 4,5 as 1**

In [ ]:
df.replace({'Rating' : { 1 : 0, 2 : 0, 3 : 0, 4 : 1, 5 : 1}}, inplace = True)

In [ ]:
y = df['Rating']

In [ ]:
X = df['Review Text']

# Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split
X_tain,X_test,y_train,y_test = train_test_split(X,y, train_size=0.7, stratify=y, random_state = 2529)

In [ ]:
X_tain.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

# Get Feature Text Conversion to Tokens

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv= CountVectorizer(lowercase = True, analyzer='word', ngram_range=(2, 3), stop_words= 'english', max_features=5000)

In [ ]:
X_train = cv.fit_transform(X_train)

In [ ]:
X_test = cv.fit_transform(X_test)

# Get Model Re-Train

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model = MultinomialNB()

In [ ]:
model.fit(X_train,y_train)

MultinomialNB()

# Get Model Prediction

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred.shape

In [ ]:
y_pred

array([1., 1., 1., ..., 1., 1., 1.])

# Get Model Evaluation

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[ 196 1387]
 [ 768 4695]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.20      0.12      0.15      1583
         1.0       0.77      0.86      0.81      5463

    accuracy                           0.69      7046
   macro avg       0.49      0.49      0.48      7046
weighted avg       0.64      0.69      0.67      7046

